### ISSUE TITLE
Divoom

### ISSUE THREAD

**Issue by bananfluen** [bursacmilan/divoom-homey#4]
Hi, thank you for a Great app!

I cant get the function render text to display?
It doest seem to work, i have tried many different settings in the render text options. Do you have any tips?

**Comment by bursacmilan** [comment]
Hi! Could you check your device’s Channel setting? It should be set to. "Custom". Also, a screenshot of your flow would help to troubleshoot.

**Comment by bananfluen** [comment]
Hi, yes have tried with the Custom channel as well.
![Screenshot_20241030_185954_Homey](https://github.com/user-attachments/assets/f5238d2f-238c-4c3d-8483-1d76c94e30b2)

**Comment by bursacmilan** [comment]
Could you first try using the "Fill screen with" flow to fill the screen with a color (like red) and see if that works?

**Comment by bursacmilan** [comment]
Also, there seems to be an issue with some of your variables. For instance, in the Y and X Position fields, the values are currently set as "27X-Position" instead of just "27." It looks like the fields for X, Y, Position, and Scroll contain incorrect values.

**Comment by bananfluen** [comment]
> Could you first try using the "Fill screen with" flow to fill the screen with a color (like red) and see if that works?

That worked! Needed to fill the screen first, then write the text. Thank you! 👍🙂
